# Generated by Django 5.1.1 on 2024-09-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='Quotation2',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
    ]
