# Generated by Django 5.1.1 on 2024-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_quotation2_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation2',
            name='post1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation2',
            name='post2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
