# Generated by Django 5.1.1 on 2024-09-29 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_rename_invoice_quotation2_delete_quotationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('days_of_duty', models.FloatField()),
                ('overtime_days', models.FloatField()),
                ('total_work_days', models.FloatField()),
                ('price_per_day', models.FloatField()),
                ('total_price', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.invoice')),
            ],
        ),
    ]
