# Generated by Django 5.0.7 on 2024-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_rename_description_item_component_remove_item_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='title',
        ),
        migrations.AddField(
            model_name='quotation',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('FRESHER', 'FRESHER (Min. 1yr experience)'), ('EXPERIENCED', 'Experienced (Min. 5 yrs)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='number_of_persons',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
