# Generated by Django 5.0.7 on 2024-08-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_remove_quotation_items_quotation_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sr_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
