# Generated by Django 5.0.7 on 2024-08-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_rename_price_item_amount_item_quantity_item_sr_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sr_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
