# Generated by Django 5.0.7 on 2024-09-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_remove_quotation_address_remove_quotation_client_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
