# Generated by Django 5.1.1 on 2024-10-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_quotation2_high_skilled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation2',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter service charge percentage.', max_digits=5, null=True),
        ),
    ]
