# Generated by Django 5.1.1 on 2024-10-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_quotation2_service_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation2',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
