# Generated by Django 5.0.7 on 2024-09-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_delete_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
