# Generated by Django 5.1.1 on 2024-09-30 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_invoice_epf_invoice_esi_invoice_gst_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='days_of_duty',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='overtime_days',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_work_days',
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('days_of_duty', models.FloatField()),
                ('overtime_days', models.FloatField()),
                ('total_work_days', models.FloatField()),
                ('price_per_day', models.FloatField()),
                ('total_price', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='quotation.invoice')),
            ],
        ),
    ]
