# Generated by Django 5.0.7 on 2024-09-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
