# Generated by Django 5.1.1 on 2024-09-30 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_remove_invoice_days_of_duty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='days_of_duty',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='employee_name',
            field=models.CharField(default='Unknown Employee', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='quotation.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='overtime_days',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='price_per_day',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='remark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_work_days',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='InvoiceDetail',
        ),
    ]
