# Generated by Django 5.0.7 on 2024-09-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0009_alter_quotation_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
