# Generated by Django 5.1.1 on 2024-09-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0009_invoice_days_of_duty_invoice_employee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation2',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
