# Generated by Django 5.0.7 on 2024-09-19 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0012_alter_job_client'),
        ('quotation', '0010_rename_create_at_quotation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_common.job'),
        ),
    ]
