# Generated by Django 5.1.1 on 2024-09-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0010_quotation2_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
