# Generated by Django 5.1.1 on 2024-09-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_invoice_email_invoice_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='phone_number',
        ),
    ]
