# Generated by Django 5.0.7 on 2024-09-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_alter_quotation_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
