# Generated by Django 5.1.1 on 2024-10-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0012_remove_invoice_email_remove_invoice_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation2',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation2',
            name='to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
