# Generated by Django 5.0.7 on 2024-09-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0013_alter_quotation_client_alter_quotation_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='email',
        ),
        migrations.AddField(
            model_name='invoice',
            name='semi_skilled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='semi_skilled_manpower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unskilled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unskilled_manpower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='working_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='working_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
