# Generated by Django 5.1.1 on 2024-10-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0014_employeedetails_delete_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='employee_details',
            field=models.JSONField(default=list),
        ),
    ]
