# Generated by Django 5.0.7 on 2024-09-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0014_remove_invoice_address_remove_invoice_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='other_allowances_semi_skilled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
