# Generated by Django 5.0.7 on 2024-09-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0015_invoice_other_allowances_semi_skilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='other_allowances_unskilled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
