# Generated by Django 5.0.7 on 2024-09-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0016_invoice_other_allowances_unskilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='operational_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reliever_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='uniform_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
