# Generated by Django 5.0.7 on 2024-09-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0017_invoice_operational_cost_invoice_reliever_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='operational_cost',
            new_name='semi_operational_cost',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='reliever_cost',
            new_name='semi_reliever_cost',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='uniform_cost',
            new_name='semi_uniform_cost',
        ),
        migrations.AddField(
            model_name='invoice',
            name='un_operational_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='un_reliever_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='un_uniform_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
