# Generated by Django 5.0.7 on 2024-09-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0018_rename_operational_cost_invoice_semi_operational_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notification_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
