# Generated by Django 5.0.7 on 2024-09-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0019_invoice_notification_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='notification_text',
            field=models.CharField(blank=True, default=True, max_length=255),
        ),
    ]
