# Generated by Django 5.0.7 on 2024-09-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0020_alter_invoice_notification_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='notification_text',
            field=models.CharField(blank=True, default='AS PER LABOUR & ESI DEPARTMENT NOTIFICATION DT. 13.03.2024, GoO', max_length=255, null=True),
        ),
    ]
