# Generated by Django 5.0.7 on 2024-10-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['created_at']},
        ),
    ]
