# Generated by Django 4.2 on 2024-03-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='hide',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
