# Generated by Django 4.2 on 2024-06-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_remove_user_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='candidates',
            field=models.ManyToManyField(related_name='job_posts', to='app_common.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='applied', max_length=50),
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('medium', models.CharField(max_length=10)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_common.userprofile')),
            ],
        ),
    ]
