# Generated by Django 5.0.7 on 2024-10-18 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemployee',
            name='client',
            field=models.ForeignKey(limit_choices_to={'is_staff': True, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='client_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_common.employee'),
        ),
    ]
