# Generated by Django 4.2 on 2024-03-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_remove_category_hide_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='generation',
        ),
        migrations.AddField(
            model_name='audiobook',
            name='narrated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
