# Generated by Django 4.2 on 2024-06-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_alter_edit_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='candidates',
            new_name='Users',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact',
            field=models.IntegerField(default=None),
        ),
    ]
