# Generated by Django 4.2 on 2024-06-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0003_job_candidates_userprofile_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
