# Generated by Django 5.0.7 on 2024-08-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0003_remove_userprofile_email_alter_application_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hiring_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hiring_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
