# Generated by Django 4.2 on 2024-06-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0003_delete_candidate_rename_candidates_job_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
