# Generated by Django 4.2 on 2024-03-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0003_remove_audiobook_generation_audiobook_narrated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='user',
        ),
    ]
