# Generated by Django 4.2 on 2024-06-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0004_alter_userprofile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
