# Generated by Django 4.2 on 2024-07-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0004_alter_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
