# Generated by Django 4.2 on 2024-03-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0004_remove_audiobook_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='duration_seconds',
        ),
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
