# Generated by Django 5.0.7 on 2024-08-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0004_application_hiring_date_application_hiring_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hiring_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='hiring_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
