# Generated by Django 4.2 on 2024-07-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0005_remove_job_client_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='uid',
        ),
    ]
