# Generated by Django 5.0.7 on 2024-08-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0005_alter_application_hiring_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='reply',
        ),
    ]
