# Generated by Django 4.2 on 2024-03-23 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0005_remove_episode_duration_seconds_episode_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='duration',
        ),
    ]
