# Generated by Django 4.2 on 2024-03-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0006_remove_episode_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='e_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
