# Generated by Django 5.0.7 on 2024-08-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0006_remove_contactmessage_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('current_employee', models.EmailField(max_length=254)),
                ('new_employee_name', models.CharField(max_length=255)),
                ('new_employee_email', models.EmailField(max_length=254)),
                ('new_employee_phone', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
