# Generated by Django 4.2 on 2024-07-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0006_remove_job_requirements_remove_job_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_common.catagory'),
        ),
    ]
