# Generated by Django 4.2 on 2024-03-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0007_episode_e_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='e_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
