# Generated by Django 4.2 on 2024-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0007_alter_userprofile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
