# Generated by Django 4.2 on 2024-07-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0008_user_profile_pic_user_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resume',
        ),
    ]
