# Generated by Django 5.1.1 on 2024-09-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0008_alter_job_company_name_alter_job_published_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
    ]
