# Generated by Django 4.2 on 2024-06-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0009_rename_category_userprofile_catagory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Users',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
