# Generated by Django 4.2 on 2024-07-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0009_remove_user_profile_pic_remove_user_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='user_resume/'),
        ),
    ]
