# Generated by Django 5.0.3 on 2024-03-25 05:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0010_alter_usersubscription_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='end_date',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
