# Generated by Django 4.2 on 2024-06-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0010_remove_job_users_alter_userprofile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
