# Generated by Django 4.2 on 2024-06-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0011_remove_userprofile_status_alter_userprofile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, unique=True),
        ),
    ]
