# Generated by Django 5.0.3 on 2024-03-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0012_remove_cart_coupon_remove_cart_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
