# Generated by Django 4.2 on 2024-06-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0012_alter_userprofile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
