# Generated by Django 4.2 on 2024-06-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0013_application_contact_application_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='publish_until',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='is_published',
            new_name='published',
        ),
        migrations.AddField(
            model_name='application',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
