# Generated by Django 5.0.3 on 2024-03-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0013_cart_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
