# Generated by Django 4.2 on 2024-07-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0013_auto_20240708_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='published',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('unpublished', 'Unpublished'), ('published', 'Published')], default='unpublished', max_length=15),
        ),
    ]
