# Generated by Django 5.0.3 on 2024-03-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0015_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_meta_data',
        ),
    ]
