# Generated by Django 4.2 on 2024-07-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0015_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app_common.application'),
        ),
    ]
