# Generated by Django 5.0.3 on 2024-03-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0016_remove_order_order_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CREDITCARD', 'CREDITCARD'), ('DEBITCARD', 'DEBITCARD'), ('COD', 'COD')], default='CREDITCARD', max_length=255),
        ),
    ]
