# Generated by Django 4.2 on 2024-06-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0016_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('read', 'Read'), ('resolved', 'Resolved')], default='pending', max_length=255),
        ),
    ]
