# Generated by Django 4.2 on 2024-07-15 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0017_employee_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='job',
            name='period_end',
            field=models.DateField(default=datetime.datetime(2024, 8, 14, 11, 54, 29, 270812)),
        ),
        migrations.AddField(
            model_name='job',
            name='period_start',
            field=models.DateField(default=datetime.datetime(2024, 7, 15, 11, 54, 29, 270812)),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
