# Generated by Django 5.0.3 on 2024-03-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0017_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CREDITCARD', 'CREDITCARD'), ('DEBITCARD', 'DEBITCARD'), ('PAYPAL', 'PAYPAL'), ('COD', 'COD')], default='CREDITCARD', max_length=255),
        ),
    ]
