# Generated by Django 5.0.3 on 2024-03-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0018_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
