# Generated by Django 4.2 on 2024-07-15 06:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0018_remove_employee_period_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='period_end',
            field=models.DateField(default=datetime.datetime(2024, 8, 14, 11, 56, 8, 691804)),
        ),
        migrations.AlterField(
            model_name='job',
            name='period_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
