# Generated by Django 4.2 on 2024-06-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0018_job_published_date_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='uid',
        ),
    ]
