# Generated by Django 4.2 on 2024-06-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0019_remove_application_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
