# Generated by Django 4.2 on 2024-07-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0019_alter_job_period_end_alter_job_period_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='job',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_min',
        ),
        migrations.AddField(
            model_name='employee',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
