# Generated by Django 4.2 on 2024-07-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0020_remove_job_period_end_remove_job_period_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
