# Generated by Django 5.0.3 on 2024-04-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0021_order_email_order_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
