# Generated by Django 4.2 on 2024-06-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0021_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('read', 'read'), ('resolved', 'resolved')], default='new', max_length=255),
        ),
    ]
