# Generated by Django 5.0.3 on 2024-04-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0022_audiobook_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
