# Generated by Django 5.0.3 on 2024-04-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0023_order_order_meta_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
