# Generated by Django 5.0.3 on 2024-05-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0024_remove_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
