# Generated by Django 5.0.3 on 2024-05-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0025_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='book_discount_price_for_members',
            field=models.FloatField(default=0.0),
        ),
    ]
