# Generated by Django 5.0.3 on 2024-05-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0026_audiobook_book_discount_price_for_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='stock',
        ),
    ]
