# Generated by Django 5.0.3 on 2024-05-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0027_remove_audiobook_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='book_discount_price_for_members',
        ),
    ]
