# Generated by Django 5.0.3 on 2024-05-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0029_remove_contactmessage_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='renewal_status',
            field=models.CharField(choices=[('taken', 'taken'), ('nottaken', 'nottaken')], default='nottaken', max_length=255),
        ),
    ]
