# Generated by Django 5.0.3 on 2024-05-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0031_listenhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenhistory',
            name='listenepisodes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
