# Generated by Django 5.0.3 on 2024-05-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0032_alter_listenhistory_listenepisodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeAPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('industry', models.CharField(max_length=100)),
                ('number_of_employees', models.IntegerField()),
                ('partnership_interest', models.TextField()),
                ('partnership_type', models.CharField(max_length=100)),
                ('past_experience', models.TextField(blank=True, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
