# Generated by Django 4.2 on 2024-06-03 10:03

import app_common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0033_becomeapartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app_common.models.banner_image_path)),
                ('show', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=255)),
                ('sl_no', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='category',
        ),
        migrations.DeleteModel(
            name='BecomeAPartner',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='audiobook',
        ),
        migrations.RemoveField(
            model_name='listenhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriptionfeatures',
            name='sub_plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='user_resume/'),
        ),
        migrations.DeleteModel(
            name='AudioBook',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='ListenHistory',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='SubscriptionFeatures',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
