# Generated by Django 4.2 on 2024-06-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0034_banner_job_remove_audiobook_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('narrated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('book_max_price', models.FloatField(default=0.0)),
                ('book_discount_price', models.FloatField(default=0.0)),
                ('release_date', models.DateField()),
                ('demo_audio_file', models.FileField(blank=True, null=True, unique=True, upload_to='demo_audio/')),
                ('language', models.CharField(max_length=50)),
                ('trending', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=255)),
                ('show_as_new', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=255)),
                ('display_as_bestseller', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=255)),
                ('hide', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=255)),
                ('audiobook_image', models.ImageField(blank=True, null=True, upload_to='audiobook_image/')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('num_ratings', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_common.category')),
            ],
        ),
    ]
