# Generated by Django 4.2 on 2024-06-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0035_audiobook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='author',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='audiobook',
            old_name='release_date',
            new_name='job_posted_date',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='audiobook_image',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='book_discount_price',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='book_max_price',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='demo_audio_file',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='display_as_bestseller',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='hide',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='language',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='narrated_by',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='trending',
        ),
    ]
