# Generated by Django 4.2 on 2024-06-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0037_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Criteria',
        ),
        migrations.RenameField(
            model_name='audiobook',
            old_name='category',
            new_name='criteria',
        ),
    ]
