# Generated by Django 4.2 on 2024-06-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0038_rename_category_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
