# Generated by Django 4.2 on 2024-06-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0040_contactmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Criteria',
            new_name='Catagory',
        ),
        migrations.RenameField(
            model_name='audiobook',
            old_name='criteria',
            new_name='catagory',
        ),
    ]
