# Generated by Django 4.2 on 2024-06-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0041_rename_criteria_catagory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='e_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_on',
        ),
        migrations.AddField(
            model_name='job',
            name='catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_common.catagory'),
        ),
        migrations.AddField(
            model_name='job',
            name='num_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='job',
            name='show_as_new',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AudioBook',
        ),
    ]
