# Generated by Django 4.2 on 2024-06-07 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0042_remove_job_e_id_remove_job_posted_on_job_catagory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Default Company Name', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='job_posted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
