# Generated by Django 4.2 on 2024-07-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0011_job_client_alter_job_job_type'),
    ]

    operations = [
    ]
